nom: Argonne Kiné Sport Santé
baseline: Kiné & Coach
adresse: 130 cours de l'Argonne
codePostal: "33000"
ville: Bordeaux
telephone: "06 69 70 46 53"
telephoneCabinet: "05 56 31 92 81"
whatsapp: "33669704653"
whatsappCoaching: "33646666621"
telephoneLelio: "06 46 66 66 21"
email: contact@argonnekinesportsante.fr
emailRuncare: runcarepro@gmail.com
doctolibRomain: https://www.doctolib.fr/masseur-kinesitherapeute/bordeaux/romain-bihel
doctolibLelio: https://www.doctolib.fr/masseur-kinesitherapeute/bordeaux/lelio-renault
instagram: https://www.instagram.com/runcare_bordeaux/
horaires: |-
  Du lundi au vendredi, sur rendez-vous.
venteUrl: https://runcare.systeme.io/748f0635
leadMagnetUrl: https://runcare.systeme.io/79081d31
googleMapsUrl: https://maps.app.goo.gl/KSetY9qE2ykRUaPY8
latitude: "44.8264897"
longitude: "-0.5766193"
googleSiteVerification: ""
umamiWebsiteId: 073abafc-4552-4729-9067-aaca1e114c03
