nom: RunCare
baseline: Kiné & Coach
adresse: 130 cours de l'Argonne
codePostal: "33000"
ville: Bordeaux
telephone: "06 69 70 46 53"
whatsapp: "33669704653"
whatsappCoaching: "33646666621"
telephoneLelio: "06 46 66 66 21"
email: contact@argonnekinesportsante.fr
doctolibRomain: https://www.doctolib.fr/masseur-kinesitherapeute/bordeaux/romain-bihel
doctolibLelio: https://www.doctolib.fr/masseur-kinesitherapeute/bordeaux/lelio-renault
instagram: ""
horaires: |-
  Du lundi au vendredi, sur rendez-vous.
leadMagnetUrl: https://runcare.systeme.io/79081d31
